#!/usr/bin/env bash
# displays hours and minutes


hour=0

while [ $hour -le 12 ]
do
	min=1
	echo "Hour:" $hour
#	((hour++))
	while [ $min -lt 60 ]
	do
		echo $min
		((min++))
	done
	
#	echo "Hour:" $hour
	((hour++))
done
