#!/usr/bin/env bash
# Script checks weather a file exists or not
# if file exists is checks weather it is empty or not

filename='./school'

if [ -e "$filename" ]
then
        echo "School file exists"

        if [ -s "$filename" ] #checks if file is not zero size
        then
                echo "School file is not empty"
        else
                echo "school file is empty"
        fi

        if [ -f "$filename" ] #checks if file is a regualr file
        then
                echo "school is a regualr file"
        fi

else
        echo "school file does not exist"
fi
