#!/usr/bin/env bash
# Script checks weather a file exists or not
# if file exists is checks weather it is empty or not


if [ -e "school" ]
then
        echo "School file exists"

        if [ -s "school" ]
        then
                echo "School file is not empty"
        else
                echo "school file is empty"
        fi

        if [ -f "school" ]
        then
                echo "school is a regualr file"
        fi

else
        echo "school file does not exist"
fi
