#!/usr/bin/env bash

# Parse Apache log file, extract IP and HTTP status code, and count occurrences

awk '{ip[$1" "$9]++ } END { for (i in ip) print ip[i], i}' apache-access.log | sort -rn | awk '{ print $1, $2, $3}'
